---
language: node_js
node_js:
  - "5.4.1"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  # See https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-177592725
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - echo $(phantomjs --version)
  - npm config set spin false

install:
  - npm install -g broccoli-cli
  - npm install -g bower
  - bower install
  - npm install

script:
  - npm run test:ci

env:
  - SAUCE_USERNAME=mobiledoc-kit SAUCE_ACCESS_KEY=f9cad21d-1141-452d-8f64-c6ba3f43faa6
